import type { Metadata } from "next";
import localFont from 'next/font/local'
import "./globals.css";

const sora = localFont({
  src: [
    {
      path: '../public/font/Sora-Bold.ttf',
      weight: '700',
      style: 'normal',
    },
    {
      path: '../public/font/Sora-Regular.ttf',
      weight: '400',
      style: 'normal',
    },
    {
      path: '../public/font/Sora-SemiBold.ttf',
      weight: '600',
      style: 'normal',
    },
  ],
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${sora.className} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
